.PHONY:gen/pb
gen/pb:
	protoc --go_out=. --go_opt=module=github.com/maooz4426/grpc-playground/greeting --go-grpc_out=. --go-grpc_opt=module=github.com/maooz4426/grpc-playground/greeting proto/greeting.proto
